### ISSUE TITLE
[table][S8.2b1][performance] issue dragging down the scrollbar thumb

### ISSUE THREAD

**Issue by p-bakker** [Servoy/servoy-extra-components#25] opened 2017-06-07 06:46 UTC
Have a table component tied to a Foundset with thousands of records.

If I scroll down using the mousewheel, new records are loaded near instantly, giving a good UX

After having scrolled down to say the 2000th record, I drag the vertical scrollbar thumb up: records are still rendered fast.

however, if I then click the vertical scrollbar thumb and drag it all the way down, the rendering of rows takes seconds. Keep dragging the thumb down to force loading records, I've seen it take up to 8 seconds (and sometimes more) for the rows to render.

It's not the queries to the database, they are lightning fast (<3ms). And I'm my database, server and client all locally, so it is not latency eitherrunning locally

**Comment by gboros** [comment] 2017-06-26 10:29
can't reproduce this, do you have a sample ? is it specific for a browser type ?

**Comment by p-bakker** [comment] 2017-07-03 12:27
Yup, still reproducible: just createa form with the grid tied to a table with say 10k records and start scrolling.

In IE the entire grid goes blank at some point. In Chrome it starts taking a while to render the rows at some point

**Comment by jcompagner** [comment] 2017-11-08 12:33
is this still a problem with the latest code?

**Comment by costescuandrei** [comment] 2017-12-22 17:40
Do you drag all the way down and keep dragging and after 8 sec you see data while still dragging?
Or do you drag all the way down, then at some point release the scroll knob and after that it takes it 8 sec to stabilize? You are not in battery saver mode (I ask because that is something that happens to me from time to time :) )?

At 10k records and after scrolling to > 2000 it would already have discarded even part of the loaded rows, not just the already rendered ones using default performance settings.

`"minBatchSizeForRenderingMoreRows" : { "type": "int", "default": 10 }`
`"minBatchSizeForLoadingMoreRows" : { "type": "int", "default": 20 },`
`"maxRenderedRows" : { "type": "int", "default": 450 },`
`"maxLoadedRows" : { "type": "int", "default": 1000 },`
`"fastScrollRenderThresholdFactor" : { "type": "int", "default": 3.0 },`
`"fastScrollLoadThresholdFactor" : { "type": "int", "default": 2.3 }`

You can play with these (lower maxes for less max content on page for slower hardware, batch sizes higher for faster/smoother scrolling once loaded or lower for faster load/render times of a batch, lower the threshholds if in case of fast scrolling you want it to jump faster (start loading/rendering only the targeted scroll content and discard everything else - don't load/render intermediate data)

I will close this as Gabi said he couldn't reproduce it. If you think it is still needs attention please reopen with sample.

**Closed by costescuandrei** 2017-12-22 17:40 UTC
